name: Ruby

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: use-ruby ${{ matrix.version }}
        uses: ./
        with:
          ruby-version: ${{ matrix.version}}

      - name: ruby version
        run: ruby -v
      # - name: Install dependencies
      #   run: bundle install
      # - name: Run tests
      #   run: ruby test/all_test.rb